version: "3.7"
services:
  app:
    restart: unless-stopped
    image: "ghcr.io/emfcamp/website:latest"
    networks:
      - emfweb
    depends_on:
      - postgres
      - memcached
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /etc/emf-site.cfg:/app/config/production.cfg
      - /etc/emf:/etc/emf
      - /var/lib/emf_vat_invoices:/vat_invoices
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      SETTINGS_FILE: ./config/production.cfg
    logging:
      driver: journald

  postgres:
    restart: unless-stopped
    image: 'postgis/postgis:13-3.1-alpine'
    volumes: 
      - /var/lib/emfweb-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - emfweb

  postgres_exporter:
    restart: unless-stopped
    image: 'wrouesnel/postgres_exporter:v0.8.0'
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/emf_site?sslmode=disable"
    networks:
      - emfweb
    ports:
      - "9187:9187"

  memcached:
    restart: unless-stopped
    image: 'memcached:1.6.13-alpine'
    networks:
      - emfweb
    command: memcached -m 64

  memcached_exporter:
    restart: unless-stopped
    image: 'prom/memcached-exporter:v0.9.0'
    depends_on:
      - memcached
    networks:
      - emfweb
    ports:
      - "9150:9150"
    command: --memcached.address memcached:11211

  static:
    restart: unless-stopped
    image: "ghcr.io/emfcamp/website-static:latest"
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "127.0.0.1:8080:80" 

  watchtower:
    restart: unless-stopped
    image: "containrrr/watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

networks:
  emfweb:
