version: "3.7"
services:
  app:
    restart: unless-stopped
    image: "ghcr.io/emfcamp/website:latest"
    networks:
      - emfweb
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /etc/emf-site.cfg:/app/config/production.cfg
      - /var/lib/emf_vat_invoices:/vat_invoices
    environment:
      SETTINGS_FILE: ./config/production.cfg
    logging:
      driver: journald

  postgres:
    restart: unless-stopped
    image: 'postgis/postgis:13-3.1-alpine'
    volumes: 
      - /var/lib/emfweb-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - emfweb


  postgres_exporter:
    restart: unless-stopped
    image: 'wrouesnel/postgres_exporter:v0.8.0'
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/emf_site?sslmode=disable"
    networks:
      - emfweb
    ports:
      - "9187:9187"

  static:
    restart: unless-stopped
    image: "ghcr.io/emfcamp/website-static:latest"
    ports:
      - "127.0.0.1:8080:80" 

networks:
  emfweb:
