name: Deploy

on: 
  push:
    branches:
      - master

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_GIT_BRANCH: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
      - name: Fetch latest docker-compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Build containers
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml build --parallel
      - name: Start environment
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml up -d
      - name: Test
        run: docker-compose -f ./docker-compose.yml -f ./docker-compose.ci.yml exec -T app poetry run make test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build app image
        run: docker build -t emfcamp/website:latest -f ./Dockerfile.prod .
      - name: Publish app image
        run: docker push emfcamp/website:latest
      - name: Build static image
        run: docker build -t emfcamp/website-static:latest -f ./docker/static/Dockerfile ./docker/static/
      - name: Publish static image
        run: docker push emfcamp/website-static:latest
